name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Run coverage
      run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

    - name: Upload coverage to Codecov
      run: bash <(curl -s https://codecov.io/bash)

    - name: Build
      run: go build -v ./...

    - name: Run
      run: ./go_comic_crawler

    - name: Check for changes
      run: |
        if git diff --exit-code; then
          echo "changes_exist=0" >> $GITHUB_ENV
        else
          echo "changes_exist=1" >> $GITHUB_ENV
        fi

    - name: update result if any
      if: ${{ env.changes_exist == '1' && github.ref == 'refs/heads/main' }}
      run: |
        git config --global user.name 'Elit Zou'
        git config --global user.email 'elit8888@gmail.com'
        git commit -am "chore: update crawl result"

    - name: Push changes
      if: ${{ env.changes_exist == '1' && github.ref == 'refs/heads/main' }}
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ main }}
